### ISSUE TITLE
[ROADMAP] Modules for Static Site Generators

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#16]
### Pre-Approval
- [x] Asked a head (Kevin) to give you write access to GitBooks
- [x] For each module: 
  - [ ] 3-4 relevant learning objectives
  - [ ] 4-5 sample activities with a one-sentence description
  - [ ] 2-3 sample labs with a one-sentence description
  - [ ] (if applicable) modules on road map before it and after it  
- [ ] GitBook Variant/GitHub branch set up with your modifications in the page "Roadmap Topic Breakdown"
- [ ] Content all correctly formatted

### Post-Approval
- [ ] Placing modules appropriately within the Lucidchart road-map

Please consult our handbook [here](https://about.bitproject.org/teams/developer-relations/development-roadmap) for any clarifications or questions!

**Comment by jeffchhen** [comment]
Module: Static Site Generators
Learning Objectives
 * Students will learn about Static Sites Generators and how they can be useful
 * Students will learn about GatsbyJS and NextJS and how to use them to generate a website
 * Students will learn about the various plugins associated with both generators 

Activities
 * When to use GatsbyJS vs NodeJS? 
    * Students will learn the advantages of using GatsbyJS and NodeJS such as how 
    * Students will learn the purposes of Static Site Generators
*  Gatsby Plugins
    * Students will integrate various API's 
    * GraphQL, Algolia will be gone over and their respective plugins
* NextJS functionality
    * TBD 


Labs
 * Build a Blog
   * Students will use a GatsbyJS to build a functional blog
 * Build a React App with NextJS 
    * TBD (cause I don't know NextJS) 

Modules Required 
* React 
* GraphQL 
* CSS/HTML
* JS

**Comment by kavuong** [comment]
@jeffchhen Hey Jeff, can you make this into a proper pull request per the handbook, and add some labs, ideally another module as well.
