### ISSUE TITLE
[ROADMAP] Modules for GraphQL

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#17]
### Pre-Approval
- [ ] Asked a head (Kevin) to give you write access to GitBooks
- [ ] For each module: 
  - [ ] 3-4 relevant learning objectives
  - [ ] 4-5 sample activities with a one-sentence description
  - [ ] 2-3 sample labs with a one-sentence description
  - [ ] (if applicable) modules on road map before it and after it  
- [ ] GitBook Variant/GitHub branch set up with your modifications in the page "Roadmap Topic Breakdown"
- [ ] Content all correctly formatted

### Post-Approval
- [ ] Placing modules appropriately within the Lucidchart road-map

Please consult our handbook [here](https://about.bitproject.org/teams/developer-relations/development-roadmap) for any clarifications or questions!

**Comment by jeffchhen** [comment]
Module: GraphQL
Learning Objectives
 * Students will have an understanding of GraphQL and how to query/insert/Mutate through data
 * Students will be able to integrate GraphQL into their applications
 * Students will be able to use GraphiQL and GraphQL playground
 * Schema and JSON/SDL formatting 

Activities
 * Query though a blog entry
    * Students will query though blog posts that can display various data 
 * Send mutations to database to store entries using GraphQL
    * Students will be able to insert and add to database 
 * Relationships with GraphQL 
    * Students will be link between various databases 

Labs ( Hard to design because GraphQL is not standalone.  It needs to be an extension off of existing knowledge) 
 * TBD
   * TBD

**Comment by jeffchhen** [comment]
> Intermediate Python

a

**Comment by kavuong** [comment]
@jeffchhen Hey Jeff, can you make this into a proper pull request per the handbook, and add some labs, ideally another module as well.

**Comment by jeffchhen** [comment]
@kavuong yes ofc.

**Comment by kavuong** [comment]
Hey @jeffchhen is there any update on this?
