### ISSUE TITLE
[ROADMAP] Modules for Blockchain

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#18]
### Pre-Approval
- [x] Asked a head (Kevin) to give you write access to GitBooks
- [x] For each module: 
  - [x] 3-4 relevant learning objectives
  - [x] 4-5 sample activities with a one-sentence description
  - [x] 2-3 sample labs with a one-sentence description
  - [x] (if applicable) modules on road map before it and after it  
- [x] GitBook Variant/GitHub branch set up with your modifications in the page "Roadmap Topic Breakdown"
- [x] Content all correctly formatted

### Post-Approval
- [x] Placing modules appropriately within the Lucidchart road-map

Please consult our handbook [here](https://about.bitproject.org/teams/developer-relations/development-roadmap) for any clarifications or questions!
