### ISSUE TITLE
[ROADMAP] Sample Issue

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#19]
**For each module**:
### Pre-Approval
- [ ] 3-4 relevant learning objectives
- [ ] 4-5 sample activities with a one-sentence description
- [ ] 2-3 sample labs with a one-sentence description
- [ ] (if applicable) modules on road map before it and after it  

### Post-Approval
- [ ] Placing modules appropriately within the Lucidchart road-map

Please consult our handbook [here](https://about.bitproject.org/teams/developer-relations/development-roadmap) for any clarifications or questions!
