### ISSUE TITLE
[ROADMAP] Modules for NoSQL/MongoDB

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#9]
### Pre-Approval
- [ ] Asked a head (Kevin) to give you write access to GitBooks
- [ ] For each module: 
  - [ ] 3-4 relevant learning objectives
  - [ ] 4-5 sample activities with a one-sentence description
  - [ ] 2-3 sample labs with a one-sentence description
  - [ ] (if applicable) modules on road map before it and after it  
- [ ] GitBook Variant/GitHub branch set up with your modifications in the page "Roadmap Topic Breakdown"
- [ ] Content all correctly formatted

### Post-Approval
- [ ] Placing modules appropriately within the Lucidchart road-map

Please consult our handbook [here](https://about.bitproject.org/teams/developer-relations/development-roadmap) for any clarifications or questions!
